version: '3.4'

services:
  gestion-congregacion.api:
    image: ${DOCKER_REGISTRY-}gestioncongregacionapi
    build:
      context: .
      dockerfile: gestion-congregacion.api/Dockerfile
    environment:
        - TZ=Etc/UTC
        - ASPNETCORE_URLS=http://+:80
        - ASPNETCORE_ENVIRONMENT=Production
  redis:
    image: bitnami/redis:latest
    environment:
        - REDIS_PASSWORD=${REDIS_PASSWORD}