version: '3.4'

services:
  gestion-congregacion.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_URLS=https://+:8081
    ports:
      - "8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  redis:
    environment:
        - REDIS_PASSWORD=dT2G10fOS94a73EIDLivwY3L7dF2bSTBK8AcrbNn
  db:
    ports:
        - "33306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=2c8sz14WYPQL
  adminer:
    image: adminer:latest
    ports:
        - "8082:8080"
    environment:
        - ADMINER_DEFAULT_SERVER=db
        - ADMINER_DEFAULT_USERNAME=root
        - ADMINER_DEFAULT_PASSWORD=2c8sz14WYPQL