version: '3.4'

services:
  gestion-congregacion.api:
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  redis:
    restart: unless-stopped
    command: redis-server --save 20 1 --loglevel warning --requirepass L5Sc89gy2LaCAodLdp949WSihMDeLif8VZ2LUAjn